name: Custom Github Docker Action
description: Call API and get user name

inputs:
  user_id:
    description: User ID, from 122 to 1000
    required: true
    default: 122
outputs:
  user_name:
    description: Getted user name

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.user_id }}
