---

name: CI
on: push

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'  # Автоматически кеширует зависимости pip
      - run: pip install -r requirements.txt
      - run: |
          ls -la
          python hello-world.py
          echo "The code is okay"

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: build-and-test  # Запускается только после успешного build-and-test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'  # Кеширование для линтера
      - run: pip install -r requirements.txt
      - run: flake8 . --extend-exclude=dist,build --show-source --statistics
