jobs:
  get_user_name_job:
    runs-on: ubuntu-latest
    # задаем значение output для этого задания
    outputs:
      user_name: ${{ steps.get_user_name_step.outputs.user_name }}
    steps:
      # 1. Сначала проверяем код репозитория
      - uses: actions/checkout@v4
      # 2. Затем используем ЛОКАЛЬНОЕ действие из текущего репозитория
      - name: Get user name
        id: get_user_name_step
        uses: tftlegal/custom-docker-action@main
        with:
          user_id: 5
      - name: Echo user name
        # получаем доступ к output предыдущего шага
        run: echo ${{ steps.get_user_name_step.outputs.user_name }}

  use_user_name_job:
    runs-on: ubuntu-latest
    needs: get_user_name_job
    steps:
      - name: Echo user name
        # получаем доступ к output предыдущего задания
        run: echo ${{needs.get_user_name_job.outputs.user_name}}
