name: Custom Action Test

on: [push]

jobs:
  get_user_name_job:
    runs-on: ubuntu-latest
    outputs:
      user_name: ${{ steps.get_user_name_step.outputs.user_name }}
    steps:
      # 1. Сначала проверяем код репозитория
      - uses: actions/checkout@v4
      
      # 2. Затем используем ЛОКАЛЬНОЕ действие из текущего репозитория
      - name: Get user name
        id: get_user_name_step
        uses: ./
        with:
          user_id: 5
          
      - name: Echo user name
        run: echo "${{ steps.get_user_name_step.outputs.user_name }}"

  use_user_name_job:
    runs-on: ubuntu-latest
    needs: get_user_name_job
    steps:
      - name: Echo user name from previous job
        run: echo "${{ needs.get_user_name_job.outputs.user_name }}"
